export const CHECKLISTS = {
  cars_and_motorcycles: [
    { id: "vin_verified", label: "VIN verified against title and listing" },
    { id: "mileage_verified", label: "Odometer reading matches listing" },
    { id: "starts_runs", label: "Vehicle starts and runs under load" },
    { id: "warning_lights", label: "No warning lights present on dashboard" },
    { id: "exterior_condition", label: "Exterior condition consistent with description" },
    { id: "interior_condition", label: "Interior condition consistent with description" },
    { id: "title_seen", label: "Title document inspected and confirmed clean" },
    { id: "seller_identity", label: "Seller identity verified in person" },
    { id: "undercarriage", label: "Undercarriage inspected for rust or damage" },
    { id: "fluids", label: "Fluid levels and quality checked" },
    { id: "tires", label: "Tires inspected for wear and safety" },
    { id: "test_drive", label: "Test drive completed successfully" },
  ],
  electronics: [
    { id: "powers_on", label: "Device powers on and boots correctly" },
    { id: "serial_number", label: "Serial number verified and documented" },
    { id: "screen_condition", label: "Screen free of cracks, dead pixels, or burn-in" },
    { id: "ports_buttons", label: "All ports and buttons functional" },
    { id: "no_theft_lock", label: "No activation lock, iCloud lock, or theft flag" },
    { id: "accessories", label: "Listed accessories present and functional" },
    { id: "battery_health", label: "Battery health within acceptable range" },
    { id: "no_water_damage", label: "No visible signs of water damage" },
  ],
  appliances: [
    { id: "powers_on", label: "Appliance powers on and operates" },
    { id: "all_functions", label: "All listed functions tested and working" },
    { id: "serial_number", label: "Serial number and model verified" },
    { id: "exterior", label: "Exterior free of major damage or rust" },
    { id: "no_leaks", label: "No visible leaks or unusual odors" },
    { id: "accessories", label: "All included accessories present" },
  ],
  jewelry_and_watches: [
    { id: "authenticity_markers", label: "Visual authenticity markers present (hallmarks, stamps)" },
    { id: "condition", label: "Overall condition consistent with description" },
    { id: "serial_engraving", label: "Serial number or engraving verified" },
    { id: "packaging_receipt", label: "Original packaging and receipt inspected" },
    { id: "no_repairs", label: "No signs of unreported repairs or alterations" },
    { id: "movement", label: "Movement or mechanism tested (watches)" },
    { id: "weight", label: "Weight consistent with authentic piece" },
  ],
  luxury_fashion_and_handbags: [
    { id: "stitching", label: "Stitching quality and pattern verified" },
    { id: "hardware", label: "Hardware markings and weight verified" },
    { id: "date_code", label: "Date code or serial tag inspected" },
    { id: "authenticity_card", label: "Authenticity card or dust bag present" },
    { id: "materials", label: "Material quality and texture consistent with brand" },
    { id: "logos", label: "Logo placement and font verified" },
    { id: "condition", label: "Condition consistent with listing description" },
  ],
  furniture: [
    { id: "structural", label: "Structural integrity confirmed" },
    { id: "dimensions", label: "Dimensions match listing" },
    { id: "materials", label: "Material type and quality verified" },
    { id: "no_pests", label: "No signs of pests or infestation" },
    { id: "finish", label: "Surface finish and upholstery condition inspected" },
    { id: "assembly", label: "All components and hardware present" },
  ],
  tools_and_equipment: [
    { id: "powers_on", label: "Tool powers on or operates under test" },
    { id: "safety_guards", label: "All safety guards and mechanisms intact" },
    { id: "wear", label: "Wear consistent with described usage" },
    { id: "blades_bits", label: "Blades, bits, or consumables condition inspected" },
    { id: "accessories", label: "Listed accessories and attachments present" },
    { id: "serial_number", label: "Serial number verified" },
  ],
  rental_or_property_verification: [
    { id: "address_confirmed", label: "Property address confirmed and matches listing" },
    { id: "landlord_identity", label: "Landlord or agent identity verified in person" },
    { id: "unit_access", label: "Physical access to unit confirmed" },
    { id: "condition", label: "Unit condition matches listing photos" },
    { id: "utilities", label: "Utilities operational and functional" },
    { id: "lease_reviewed", label: "Lease document reviewed for legitimacy" },
    { id: "no_liens", label: "No signs of fraud, prior evictions, or liens" },
  ],
  other: [
    { id: "item_present", label: "Item confirmed present in person" },
    { id: "matches_listing", label: "Item matches listing description and photos" },
    { id: "condition", label: "Condition accurately represented" },
    { id: "seller_identity", label: "Seller identity verified" },
    { id: "no_concerns", label: "No significant red flags observed" },
  ],
};

export function getChecklist(category) {
  return CHECKLISTS[category] || CHECKLISTS.other;
}